# Generated by Django 3.2.25 on 2024-06-22 17:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'slopes',
                'db_table': 'slopes',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
