# Generated by Django 3.2.25 on 2024-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0002_auto_20240622_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='slope',
            name='difficulty',
            field=models.CharField(default='Blue', max_length=100),
        ),
    ]
