# Generated by Django 3.2.25 on 2024-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0004_alter_slope_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slope',
            name='difficulty',
            field=models.CharField(choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red'), ('black', 'black')], default='green', max_length=100),
        ),
    ]
