# Generated by Django 3.2.25 on 2024-06-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0005_alter_slope_difficulty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
