# Generated by Django 3.2.25 on 2024-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0008_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='slope',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='closed', max_length=100),
        ),
    ]
