# Generated by Django 3.2.25 on 2024-06-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0011_remove_lift_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
