# Generated by Django 3.2.25 on 2024-06-23 13:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0012_delete_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('type', models.CharField(choices=[('restaurant', 'restaurant'), ('hotel', 'hotel'), ('liftstation', 'liftstation')], default='restaurant', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'buildings',
                'db_table': 'buildings',
            },
        ),
        migrations.AlterField(
            model_name='lift',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
    ]
