# Generated by Django 3.2.25 on 2024-06-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0013_auto_20240623_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buildings',
            new_name='Building',
        ),
    ]
