# Generated by Django 3.2.25 on 2024-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0014_rename_buildings_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='closed', max_length=100),
        ),
        migrations.AddField(
            model_name='slope',
            name='type',
            field=models.CharField(choices=[('chairlift', 'chairlift'), ('gondola', 'gondola'), ('teleski', 'teleski')], default='chairlift', max_length=100),
        ),
    ]
