# Generated by Django 3.2.25 on 2024-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0015_auto_20240623_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slope',
            name='type',
        ),
        migrations.AddField(
            model_name='lift',
            name='type',
            field=models.CharField(choices=[('chairlift', 'chairlift'), ('gondola', 'gondola'), ('teleski', 'teleski')], default='chairlift', max_length=100),
        ),
    ]
